name: "pip-publish"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "PipPublish"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "setup"
        run: |
          make setup-pip-build-env
        working-directory: "."

      - name: "build"
        run: |
          make pip-build
        working-directory: "."

      - name: "publish"
        id: publish
        run: |
          python3 -m twine upload -u __token__ -p "${{ secrets.PYPI_SECRET }}" pip-build/*
        working-directory: "."
