name: "release"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: execname
        run: echo "::set-output name=exe::$(make exec-file)"

      - run: pip3 install cython

      - run: "make && make compile"
        working-directory: "."

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$tag" \
              --generate-notes

      - name: upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload "$tag" \
            ./${{ steps.execname.outputs.exe }}
        working-directory: "."
